# Generated by Django 4.2.7 on 2026-01-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blueprint",
            name="body_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="blueprintfield",
            name="position_label",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
